[package]
name = "todo_term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
humantime = "2.1.0"
