[package]
name = "todo_term"
version = "1.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
humantime = "2.1.0"
surrealdb = "1.3.1"
tokio = "1.37.0"